name: mail-relay

networks:
  mail:
    name: mail
    ipam:
      config:
        - subnet: 172.172.0.0/16

services:
  postfix:
    build: build/postfix
    restart: always
    container_name: mail
    hostname: mail
    volumes:
      - ./data/main.cf:/etc/postfix/main.cf
      - ./data/saslpass.db:/etc/postfix/saslpass.db
    networks:
      - mail
    # Uncomment for testing only
    # ports:
    #   - "25:25"
