name: mail-relay

networks:
  mail:
    external: true
services:
  postfix:
    build: build/postfix
    restart: always
    container_name: mail
    hostname: mail
    volumes:
      - ./data/main.cf:/etc/postfix/main.cf
      - ./data/saslpass.db:/etc/postfix/saslpass.db
    networks:
      - mail
      - default
