version: '3'
networks:
  mail:
    external: true
services:
  postfix:
    build: postfix
    restart: always
    container_name: mail
    hostname: mail
    volumes:
      - ./main.cf:/etc/postfix/main.cf
      - ./saslpass.db:/etc/postfix/saslpass.db
    networks:
      - mail
      - default
